{% set PKG_NAME = 'protoc' %}
{% set VERSION = '3.1.0' %}
package:
  name: {{ PKG_NAME }}
  version: {{ VERSION }}

source:
  url: https://github.com/google/protobuf/releases/download/v3.1.0/protoc-3.1.0-win32.zip  # [win]

build:
  number: 0
  skip: true  # [not win]
