package:
  name: json-tricks
  version: 3.8.0

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 0
  script: python -m pip install "json-tricks==3.8.0"

requirements:
  build:
    - python

  run:
    - python

test:
  imports:
    - json_tricks

about:
  licence: BSD-3
  url: https://github.com/mverleg/pyjson_tricks
