package:
  name: ntfsutils
  version: 0.1.3

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 1
  script: python setup.py install --single-version-externally-managed --record=record.txt
  noarch: python

source:
  url: https://github.com/sid0/ntfs/archive/0.1.3.tar.gz

requirements:
  build:
    - python
    - pip

test:
  imports:
    - ntfsutils.fs
    - ntfsutils.hardlink
    - ntfsutils.junction

about:
  licence: BSD
  url: https://github.com/sid0/ntfs
  author:
    - Siddharth Agarwal (sid0)
    - Roman Lacko (rlacko)
    - Barry Pederson (barryp)
    - Philippe Ombredanne (pombredanne)
