{% set PKG_NAME = 'arduino-fast-digital' %}
{% set LIB_NAME = 'FastDigital' %}
{% set VERSION = '0.1.0' %}
package:
  name: {{ PKG_NAME }}
  version: {{ VERSION }}

source:
  path: .

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 2
  noarch: generic
  script:
    - python -c
      "import os.path; import os; import shutil; import platformio_helpers as pioh;
      install_dir = pioh.conda_arduino_include_path().joinpath('{{ LIB_NAME }}');
      os.makedirs(install_dir);
      shutil.copy2(os.path.join(os.environ['SRC_DIR'], '{{ LIB_NAME }}.h'),
                   os.path.join(install_dir, '{{ LIB_NAME }}.h'));
      "

requirements:
  build:
    - platformio-helpers >=0.6
    - python
