{% set PKG_NAME = "ragel" %}
{% set VERSION = "6.10" %}
package:
  name: {{ PKG_NAME }}
  version: {{ VERSION }}

source:  # [win]
  url: https://github.com/sci-bots/{{ PKG_NAME }}/releases/download/{{ PKG_NAME }}-{{ VERSION }}/{{ PKG_NAME }}-{{ VERSION}}-win32.exe  # [win]
  url: https://github.com/sci-bots/{{ PKG_NAME }}/archive/{{ PKG_NAME }}-{{ VERSION }}.tar.gz  # [not win]

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 0
  script:  # [win]
    - mkdir "%PREFIX%/Library/bin"  # [win]
    - move "%SRC_DIR%\{{ PKG_NAME }}-{{ VERSION}}-win32.exe" "%PREFIX%\Library\bin\{{ PKG_NAME }}.exe"  # [win]

requirements:
  build:
    - automake  # [not win]
