{% set PKG_NAME = 'crum' %}
{% set version = '0.1' %}

source:
  url: ..

package:
  name: {{ PKG_NAME }}
  version: {{ version }}

build:
  script: python setup.py install --single-version-externally-managed --record record.txt
  noarch: python

requirements:
  build:
    - click
    - conda-helpers
    - git
    - gitpython
    - joblib
    - networkx
    - pydash
    - python
    - path_helpers
    - ruamel.yaml
    - semantic_version

  run:
    - click
    - conda-helpers
    - git
    - gitpython
    - joblib
    - networkx
    - pydash
    - python
    - path_helpers
    - ruamel.yaml
    - semantic_version

test:
  imports:
    - crum

about:
  home: https://github.com/sci-bots/{{ PKG_NAME }}
  license: BSD
