{% set name = 'paho-mqtt' %}
{% set version = '1.3.1' %}
package:
    name: {{ name }}
    version: {{ version }}

source:
    url: https://pypi.python.org/packages/2a/5f/cf14b8f9f8ed1891cda893a2a7d1d6fa23de2a9fb4832f05cef02b79d01f/{{ name }}-{{ version }}.tar.gz
    md5: 2cc27d8b369700b1fc99325add0dadd2

build:
    number: 1
    script: python setup.py install --single-version-externally-managed --record=record.txt
    noarch: python

requirements:
    build:
        - python

    run:
        - python

test:
    imports:
        - paho.mqtt.client
        - paho.mqtt.subscribe
        - paho.mqtt.publish

about:
  home: https://github.com/sci-bots/paho-mqtt-recipe
  license: Eclipse Public License v1.0 / Eclipse Distribution License v1.0
