{% set name = 'paho-mqtt' %}
{% set version = '1.2.3' %}
package:
    name: {{ name }}
    version: {{ version }}

source:
    url: https://pypi.python.org/packages/ce/27/28ac0859fb8d63754ec51659be265bf3b89d1568c5f6736d21026e11ea85/{{ name }}-{{ version }}.tar.gz
    md5: 4bd192ea24e7aa347f6d240101ef82f6

build:
    number: 1
    script: python setup.py install --single-version-externally-managed --record=record.txt
    noarch: python

requirements:
    build:
        - python

    run:
        - python

test:
    imports:
        - paho.mqtt.client
        - paho.mqtt.subscribe
        - paho.mqtt.publish

about:
  home: https://github.com/sci-bots/paho-mqtt-recipe
  license: Eclipse Public License v1.0 / Eclipse Distribution License v1.0
