{% set PKG_NAME = 'nanopb' %}
{% set VERSION = '0.3.7' %}
package:
  name: {{ PKG_NAME }}
  version: {{ VERSION }}

source:
  url: https://koti.kapsi.fi/~jpa/nanopb/download/{{ PKG_NAME }}-{{ VERSION }}.tar.gz

build:
  number: 0

requirements:
  build:
    - protoc # [win]
    - protobuf # [not win]
    - python {{ python }}

  run:
    - python {{ python }}
    - protoc # [win]
    - protobuf # [not win]
