{% set VERSION = "5.0.0" %}
package:
  name: python-clang
  version: {{ VERSION }}

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 1
  noarch: python

requirements:
  build:
    - clang {{ VERSION }}
    - cmake # [not win]
    - curl # [win]
    - gcc # [not win]
    - m2-p7zip >=9.38.1 # [win]
    - python

  run:
    - {{ pin_compatible('clang') }}
    - python

test:
  imports:
    - clang >=5.0.0
    - clang.cindex
    - clang.enumerations
