package:
  name: conda-env-exec
  version: 0.1.0

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 0
  noarch: true

requirements:
  run:
    - conda-wrappers
