{% set PKG_NAME = 'arduino-linked-list' %}
{% set LIB_NAME = 'LinkedList' %}
{% set VERSION = '1.2.3' %}
{% set GITHUB_USER = 'ivanseidel' %}
package:
  name: {{ PKG_NAME }}
  version: {{ VERSION }}

source:
  url: https://github.com/{{ GITHUB_USER }}/{{ LIB_NAME }}/archive/{{ VERSION }}.tar.gz

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 4
  noarch: generic
  script:
    python -c
      "import os.path; import os; import shutil; import platformio_helpers as pioh;
      install_dir = pioh.conda_arduino_include_path().joinpath('{{ LIB_NAME }}');
      shutil.copytree(os.environ['SRC_DIR'], install_dir);
      BUILD_SCRIPT = os.path.join(install_dir, 'bld.bat');
      BUILD_SCRIPT = BUILD_SCRIPT if os.path.isfile(BUILD_SCRIPT) else os.path.join(install_dir, 'build.sh');
      os.remove(BUILD_SCRIPT);
      "

requirements:
  build:
    - platformio-helpers >=0.6
    - python
